### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by jwjw2069** [Braindrool/Titanfall2-Aimbot-ESP#1]
There is no way to inject without crash

**Comment by maxigator** [comment]
inject while in game and uninject on the menu not on the loading screen

**Comment by jwjw2069** [comment]
I just get this msg https://gyazo.com/de403dc57db9776d532fcb828283d6ac

**Comment by maxigator** [comment]
to inject you have to download a game injector (i recommend using [process hacker] https://processhacker.sourceforge.io/downloads.php)) 
When your process hacker screen is showing a list of all you programs, you search for the titanfall 2 process
![image](https://user-images.githubusercontent.com/22241832/113419445-be92d180-93c7-11eb-812d-4887a4e4a526.png)
You right click, and go to miscellaneous and click on Inject dll...
![image](https://user-images.githubusercontent.com/22241832/113419514-e5e99e80-93c7-11eb-8acb-b633e15a6cb3.png)
Select your dll file and there you go !
(Remember that you have to be in a game fro this to work and in **windowed mode**!!!

**Comment by jwjw2069** [comment]
Thanks i can inject it now butttt, when ever i tab into the game it makes my screen go black then crashes

**Comment by jwjw2069** [comment]
After injecting ingame i get this https://gyazo.com/73f2d6f4d35206598a2b3c4425bdadc8

**Comment by jwjw2069** [comment]
https://streamable.com/z0zj6i 
Where it finishes where my whole screen blanks and where the game crashes with a memory error

**Comment by maxigator** [comment]
try this : 
Disable origin overlay in the origin game settings
Disable steam (if you have it on steam) overlay too

**Comment by maxigator** [comment]
I know everybody says this, but you should update your graphics drivers ([nvidia geforce experience](https://www.nvidia.com/fr-fr/geforce/geforce-experience/download/) if you have nvidia)
and also **try to launch origin with admin powers**

**Comment by maxigator** [comment]
and if you overclock your gpu you should either turn it down or stop completely

**Comment by maxigator** [comment]
_"It seemed to me like it was crashing in that environment when impact and effects where on. "_  [source](https://answers.ea.com/t5/Titanfall-2/PC-Error-code-0x887A0006-DXGI-ERROR-DEVICE-HUNG-can-t-play-game/td-p/5661394)

**Comment by jwjw2069** [comment]
It works now. Had to turn off overlay but ive got a bug for ya
